secret/config/routes.rb
Rails.application.routes.draw do

	resources :users
	root to: 'static_pages#home'


	get 'static_pages/secret_page', to:'static_pages#secret_page'

	get    '/signup',  to: 'users#new'
	post   '/signup',   to: 'users#create'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	post   '/users/:id/edit(.:format)',   to: 'users#edit'
	get    '/users/:id/user/destroy(.:format)', to: 'users#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

secret/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

secret/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

secret/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

secret/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		def create
			user = User.find_by(email: params[:session][:email].downcase)
			if user && user.authenticate(params[:session][:password])
				log_in user
				redirect_to user

			else
				flash.now[:danger] = 'Invalid email/password combination'
				render 'new'
			end
		end
	end

	def destroy
		log_out
		redirect_to root_url
	end
end

secret/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def secret_page
		unless logged_in?
			flash[:danger] = " Tu dois te connecter d'abord ;)"
			redirect_to login_path
			
		end
	end
end

secret/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new	
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:success] = "Welcome VIP"
			redirect_to @user
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to @user
		else 
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			redirect_to root_path
			flash[:success] = 'account deleted'
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

end

secret/app/helpers/application_helper.rb
module ApplicationHelper
end

secret/app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user.
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	# Returns true if the user is logged in, false otherwise.
	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

end

secret/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

secret/app/helpers/users_helper.rb
module UsersHelper
end

secret/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

secret/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Secret</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<!-- Latest compiled and minified CSS -->

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">



	<!-- Optional theme -->

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">



	<!-- Latest compiled and minified JavaScript -->

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>

<%= render "layouts/header" %>

<body style="margin-top: 150px;">

      
	

	


	<%= yield %>

</body>
</html>

secret/app/views/static_pages/home.html.erb
<div style="text-align: center;">

<h1 class="w3-text-orange" class="w3-jumbo" class = w3-section style="text-shadow:1px 1px 0 #444">COMPLOTS</h1>

	<p>Tu veux connaître la réponse à la question secrète de l'univers ?</p>

<img src = "https://media.giphy.com/media/W7gYes8gffrS8/giphy.gif" class = w3-section alt = "secret" >
<p>Clique ici !<%= link_to "Secrete Page",   '/static_pages/secret_page' %></p>
</div>

secret/app/views/static_pages/secret_page.html.erb
<div style="text-align: center;">

<h1 class="w3-text-orange" class="w3-jumbo" class = w3-section style="text-shadow:1px 1px 0 #444">TOUCH MY TRALALA</h1>

<iframe width="854" height="480" src="https://www.youtube.com/embed/tzfxyUC4AO0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>" 
</div>

secret/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

secret/app/views/users/edit.html.erb
<div style="text-align: center;">
	<h1>Edit</h1>


	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_for@user do |f| %>


			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Edit your profile", class: "btn btn-primary" %>
			<% end %>
                  
                 <button type="button" class="btn btn-danger"><%= link_to 'Delete this account', 'user/destroy'  %></button>

		</div>
	</div>
</div>

secret/app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: signup_path) do |f| %>


      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

       <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Sign Up", class: "btn btn-primary" %>
    <% end %>

   
  </div>
</div>

secret/app/views/users/show.html.erb
<div style="text-align: center;">

	<h1> <%= @user.name %>'s profile</h1>

	<h2> Ton email : </h2>
	<p><%= @user.email %></p>

	<h2> Ton nom : </h2>
	<p><%= @user.name %></p>
	<% if logged_in? && @user == @current_user %>
	<p><%= link_to 'Editer mon profil', edit_user_path(@user) %></p>
	<% end %>
</div>